"""events and event rsvps

General-purpose calendar-events domain (distinct from coaching Sessions and
Tournaments). Adds:
  - events table (owner + targeting via audience: everyone/band/coach_group/individual)
  - event_rsvps table (unique on event_id + user_id)
and their Postgres enums (event_audience, event_status, event_rsvp_status).

Purely additive: the autogenerated junior_profiles featured_badge FK
drop/recreate (pre-existing drift, unrelated to this domain) was removed.

Revision ID: 458277fd31e2
Revises: o16seedbadges
Create Date: 2026-06-15

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '458277fd31e2'
down_revision = 'o16seedbadges'
branch_labels = None
depends_on = None


event_audience = sa.Enum(
    "everyone", "band", "coach_group", "individual", name="event_audience"
)
event_status = sa.Enum("scheduled", "cancelled", name="event_status")
event_rsvp_status = sa.Enum("going", "not_going", name="event_rsvp_status")

ENUMS = (event_audience, event_status, event_rsvp_status)


def _enum(name, *values):
    """Reference an enum created above without re-issuing CREATE TYPE."""
    return postgresql.ENUM(*values, name=name, create_type=False)


def upgrade():
    bind = op.get_bind()
    for enum in ENUMS:
        enum.create(bind, checkfirst=True)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column(
            "audience",
            _enum("event_audience", "everyone", "band", "coach_group", "individual"),
            nullable=False,
        ),
        sa.Column("band_id", sa.Integer(), nullable=True),
        sa.Column("coach_id", sa.String(length=36), nullable=True),
        sa.Column("junior_id", sa.Integer(), nullable=True),
        sa.Column("rsvp_required", sa.Boolean(), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            _enum("event_status", "scheduled", "cancelled"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["band_id"], ["level_bands.id"]),
        sa.ForeignKeyConstraint(["coach_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["junior_id"], ["junior_profiles.id"]),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "event_rsvps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            _enum("event_rsvp_status", "going", "not_going"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_event_rsvps_event_user"),
    )


def downgrade():
    op.drop_table("event_rsvps")
    op.drop_table("events")
    bind = op.get_bind()
    for enum in reversed(ENUMS):
        enum.drop(bind, checkfirst=True)
