"""baseline schema (all domains incl. tournaments)

Revision ID: 94e5c8f92486
Revises: 
Create Date: 2026-06-07 12:17:25.051478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e5c8f92486'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('altitude_ft', sa.Integer(), nullable=True),
    sa.Column('grass_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('band_label', sa.String(length=100), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('min_sessions', sa.Integer(), nullable=False),
    sa.Column('report_template', sa.Enum('skills', 'practice_scores', 'competition', name='level_band_report_template'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('min_level >= 1 AND max_level >= min_level', name='ck_level_bands_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('min_level', 'max_level', name='uq_level_bands_range')
    )
    op.create_table('level_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('full_swing_target', sa.Integer(), nullable=False),
    sa.Column('around_green_target', sa.Integer(), nullable=False),
    sa.Column('putting_target', sa.Integer(), nullable=False),
    sa.Column('nine_hole_target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_number')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('points_scheme', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=1000), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('admin', 'coach', 'committee', 'parent', 'player', name='user_role'), nullable=False),
    sa.Column('membership_type', sa.Enum('full', 'social', 'guest', 'junior', name='user_membership_type'), nullable=False),
    sa.Column('handicap_index', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('cdh_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('handicap_index IS NULL OR handicap_index BETWEEN -10.0 AND 54.0', name='ck_users_handicap_index'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['level_bands.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('stroke_index', sa.Integer(), nullable=False),
    sa.Column('white_yards', sa.Integer(), nullable=False),
    sa.Column('yellow_yards', sa.Integer(), nullable=False),
    sa.Column('blue_yards', sa.Integer(), nullable=False),
    sa.Column('red_yards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hole_number BETWEEN 1 AND 18', name='ck_holes_hole_number'),
    sa.CheckConstraint('par IN (3, 4, 5)', name='ck_holes_par'),
    sa.CheckConstraint('stroke_index BETWEEN 1 AND 18', name='ck_holes_stroke_index'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'hole_number', name='uq_holes_course_hole_number'),
    sa.UniqueConstraint('course_id', 'stroke_index', name='uq_holes_course_stroke_index')
    )
    op.create_table('junior_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='junior_gender'), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('curriculum', sa.String(length=255), nullable=True),
    sa.Column('has_handicap', sa.Boolean(), nullable=False),
    sa.Column('handicap_index', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('played_us_kids', sa.Boolean(), nullable=True),
    sa.Column('us_kids_best_score', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Enum('beginner', 'lt_1yr', '1_3yr', '4_6yr', '7_10yr', name='junior_experience'), nullable=False),
    sa.Column('availability', sa.Enum('twice_weekly', 'weekends_only', 'more_than_twice', 'holidays_only', name='junior_availability'), nullable=False),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('golf_goals', sa.Text(), nullable=True),
    sa.Column('tournament_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_level BETWEEN 1 AND 9', name='ck_juniors_current_level'),
    sa.ForeignKeyConstraint(['band_id'], ['level_bands.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tee_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('white', 'yellow', 'blue', 'red', name='tee_set_name'), nullable=False),
    sa.Column('gender', sa.Enum('men', 'women', name='tee_set_gender'), nullable=False),
    sa.Column('course_rating', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('slope_rating', sa.Integer(), nullable=False),
    sa.Column('total_yards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('slope_rating BETWEEN 55 AND 155', name='ck_tee_sets_slope_rating'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'name', 'gender', name='uq_tee_sets_course_name_gender')
    )
    op.create_table('class_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'dropped', name='class_enrollment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['junior_id'], ['junior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'junior_id', name='uq_class_enrollments_class_junior')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('attendance_count', sa.Integer(), nullable=False),
    sa.Column('attendance_total', sa.Integer(), nullable=True),
    sa.Column('assessment', sa.Enum('below_expectation', 'meeting_expectation', 'exceeding_expectation', name='evaluation_assessment'), nullable=False),
    sa.Column('recommendation', sa.Enum('continue_level', 'move_next_level', name='evaluation_recommendation'), nullable=False),
    sa.Column('special_remarks', sa.Text(), nullable=True),
    sa.Column('putting_assessment', sa.Text(), nullable=True),
    sa.Column('chipping_assessment', sa.Text(), nullable=True),
    sa.Column('full_swing_assessment', sa.Text(), nullable=True),
    sa.Column('avg_score_9', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('avg_score_18', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('competitions_played', sa.Integer(), nullable=True),
    sa.Column('best_gross_score', sa.Integer(), nullable=True),
    sa.Column('coach_signed', sa.Boolean(), nullable=False),
    sa.Column('coach_signed_date', sa.Date(), nullable=True),
    sa.Column('committee_signed', sa.Boolean(), nullable=False),
    sa.Column('committee_signed_date', sa.Date(), nullable=True),
    sa.Column('committee_signed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('committee_signed = false OR coach_signed = true', name='ck_evaluations_signoff_order'),
    sa.CheckConstraint('current_level BETWEEN 1 AND 9', name='ck_evaluations_current_level'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['committee_signed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['junior_id'], ['junior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('junior_id', 'report_month', name='uq_evaluations_junior_report_month')
    )
    op.create_table('junior_badges',
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('awarded_date', sa.Date(), nullable=False),
    sa.Column('awarded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['junior_id'], ['junior_profiles.id'], ),
    sa.PrimaryKeyConstraint('junior_id', 'badge_id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('tee_set_id', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.Date(), nullable=False),
    sa.Column('round_type', sa.Enum('casual', 'tournament', 'competition', name='round_type'), nullable=False),
    sa.Column('competition_name', sa.String(length=255), nullable=True),
    sa.Column('gross_score', sa.Integer(), nullable=False),
    sa.Column('adjusted_gross_score', sa.Integer(), nullable=True),
    sa.Column('score_differential', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('pcc_adjustment', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('handicap_before', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('handicap_after', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['tee_set_id'], ['tee_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('session_type', sa.Enum('group', 'one_on_one', 'evaluation', 'tournament_prep', name='session_type'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='session_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.Enum('stroke_play', 'stableford', 'match_play', name='tournament_format'), nullable=False),
    sa.Column('scoring_basis', sa.Enum('gross', 'net', 'both', name='tournament_scoring_basis'), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('tee_set_id', sa.Integer(), nullable=True),
    sa.Column('holes', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('counts_toward_handicap', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'registration_open', 'registration_closed', 'in_progress', 'completed', 'cancelled', name='tournament_status'), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('max_entrants', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('level_min', sa.Integer(), nullable=True),
    sa.Column('level_max', sa.Integer(), nullable=True),
    sa.Column('handicap_min', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('handicap_max', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('handicap_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('holes IN (9, 18)', name='ck_tournaments_holes'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['tee_set_id'], ['tee_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'excused', name='attendance_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['junior_id'], ['junior_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'junior_id', name='uq_attendance_session_junior')
    )
    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='booking_request_status'), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['junior_id'], ['junior_profiles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('faldo_series', 'us_kids', 'jgf', 'karen_open', 'other', name='external_event_type'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('holes', sa.Integer(), nullable=True),
    sa.Column('gross_score', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('field_size', sa.Integer(), nullable=True),
    sa.Column('counts_toward_handicap', sa.Boolean(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('logged_by', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['junior_id'], ['junior_profiles.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hole_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.Column('putts', sa.Integer(), nullable=True),
    sa.Column('fairway_hit', sa.Boolean(), nullable=True),
    sa.Column('gir', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hole_number BETWEEN 1 AND 18', name='ck_hole_scores_hole_number'),
    sa.CheckConstraint('strokes > 0', name='ck_hole_scores_strokes'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'hole_number', name='uq_hole_scores_round_hole')
    )
    op.create_table('tournament_divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('basis', sa.Enum('age', 'gender', 'level', 'handicap', 'custom', name='division_basis'), nullable=False),
    sa.Column('tee_set_id', sa.Integer(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('level_min', sa.Integer(), nullable=True),
    sa.Column('level_max', sa.Integer(), nullable=True),
    sa.Column('handicap_min', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('handicap_max', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tee_set_id'], ['tee_sets.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('registered_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('registered', 'confirmed', 'withdrawn', name='entry_status'), nullable=False),
    sa.Column('registered_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['tournament_divisions.id'], ),
    sa.ForeignKeyConstraint(['junior_id'], ['junior_profiles.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'junior_id', name='uq_entries_tournament_junior')
    )
    op.create_table('tournament_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('bracket_position', sa.Integer(), nullable=False),
    sa.Column('player_a_entry_id', sa.Integer(), nullable=True),
    sa.Column('player_b_entry_id', sa.Integer(), nullable=True),
    sa.Column('winner_entry_id', sa.Integer(), nullable=True),
    sa.Column('result_text', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', name='match_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_a_entry_id'], ['tournament_entries.id'], ),
    sa.ForeignKeyConstraint(['player_b_entry_id'], ['tournament_entries.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_entry_id'], ['tournament_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('holes_played', sa.Integer(), nullable=False),
    sa.Column('gross_score', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Integer(), nullable=True),
    sa.Column('stableford_points', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'verified', name='score_status'), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['tournament_entries.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', name='uq_scores_entry')
    )
    op.create_table('tournament_hole_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_score_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hole_number BETWEEN 1 AND 18', name='ck_thole_hole_number'),
    sa.CheckConstraint('strokes > 0', name='ck_thole_strokes'),
    sa.ForeignKeyConstraint(['tournament_score_id'], ['tournament_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_score_id', 'hole_number', name='uq_thole_score_hole')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_hole_scores')
    op.drop_table('tournament_scores')
    op.drop_table('tournament_matches')
    op.drop_table('tournament_entries')
    op.drop_table('tournament_divisions')
    op.drop_table('hole_scores')
    op.drop_table('external_results')
    op.drop_table('booking_requests')
    op.drop_table('attendance')
    op.drop_table('tournaments')
    op.drop_table('sessions')
    op.drop_table('rounds')
    op.drop_table('junior_badges')
    op.drop_table('evaluations')
    op.drop_table('class_enrollments')
    op.drop_table('tee_sets')
    op.drop_table('junior_profiles')
    op.drop_table('holes')
    op.drop_table('classes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('series')
    op.drop_table('level_benchmarks')
    op.drop_table('level_bands')
    op.drop_table('courses')
    op.drop_table('badges')
    # ### end Alembic commands ###
